apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-autosync-exporter
  labels:
    app: argocd-autosync-exporter
data:
  config.yaml: |
    # listenAddress -- address to bind the server
    listenAddress: 0.0.0.0:8080
    # scrape_interval -- interval for scraping autosync status from target argocd in seconds
    scrape_interval: 15
    # argocd -- argocd settings
    argocd:
      # argocd.instance -- argocd target instance
      instance: 'argocd-server.argocd'
