apiVersion: v1
kind: Service
metadata:
  name: argocd-autosync-exporter
  labels:
    app: argocd-autosync-exporter
spec:
  type: ClusterIP
  selector:
    app: argocd-autosync-exporter
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
